# Schema for cmis_alfresco_auth_user.

cmis_alfresco_auth_user.settings:
  type: config_object
  label: 'CMIS Alfresco Auth User settings'
  mapping:
    alfresco_tickets_endpoint_url:
      type: uri
      label: 'Alfresco tickets endpoint URL'
