cmis.cmis_connection_entity.*:
  type: config_entity
  label: 'CMIS connection config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    cmis_url:
      type: string
      label: 'CMIS url'
    cmis_user:
      type: string
      label: 'CMIS user name'
    cmis_password:
      type: string
      label: 'CMIS password'
    cmis_repository:
      type: string
      label: 'CMIS repository'
    cmis_root_folder:
      type: string
      label: 'CMIS root folder'
    cmis_cacheable:
      type: boolean
      label: 'CMIS cacheable'
